### ISSUE TITLE
When double clicking on application, an error occurs, due to manifest signature

### ISSUE THREAD

**Issue by airdalle** [ramonck/NintexWorkflowAnalyzer#1]
Log is the  follwoing : 
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2558.0 built by: NET471REL1
	clr.dll 			: 4.7.2558.0 built by: NET471REL1
	dfdll.dll 			: 4.7.2558.0 built by: NET471REL1
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: file:///C:/NWA-GitHub/dist/WorkflowAnalyzer.application
	Deployment Provider url		: https://workflowanalyzer.codeplex.com/releases/clickonce/WorkflowAnalyzer.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\NWA-GitHub\dist\WorkflowAnalyzer.application resulted in exception. Following failure messages were detected:
		+ The Deployment Provider specified in the manifest cannot be reached. Maybe due to network error and/or the deployment provider is not responding correctly.
		+ Exception reading manifest from https://archive.codeplex.com/?p=workflowanalyzer: the manifest may not be valid or the file could not be opened.
		+ DTD is prohibited in this XML document.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [13/02/2018 10:46:36] : Activation of C:\NWA-GitHub\dist\WorkflowAnalyzer.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [13/02/2018 10:46:37] System.Deployment.Application.InvalidDeploymentException (Manifest)
		- The Deployment Provider specified in the manifest cannot be reached. Maybe due to network error and/or the deployment provider is not responding correctly.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from https://archive.codeplex.com/?p=workflowanalyzer: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
		--- Inner Exception ---
		System.Xml.XmlException
		- DTD is prohibited in this XML document.
		- Source: System.Xml
		- Stack trace:
			at System.Xml.XmlTextReaderImpl.Throw(Exception e)
			at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
			at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
			at System.Deployment.Application.ManifestValidatingReader.XmlFilteredReader.Read()
			at System.Xml.XsdValidatingReader.Read()
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by ramonck** [comment]
Hi @airdalle ,

This is because you didn't remove the old link in your desktop, you're still referencing the old installation.
`+ Exception reading manifest from https://archive.codeplex.com/?p=workflowanalyzer: the manifest may not be valid or the file could not be opened.`

1. Please remove this shortcut in your desktop (The old version).
2. Download from the releases https://github.com/ramonck/NintexWorkflowAnalyzer/releases
3. Follow the Installation instructions and you should be all set: https://github.com/ramonck/NintexWorkflowAnalyzer/

Best Regards,

**Comment by airdalle** [comment]
Actually I created a new shortcut on my desktop and double clicked on it. As it didn't worked,  I went to C:\NWA-GitHub\dist\Application Files\WorkflowAnalyzer_1_4_0_39 folder and double clicked, IN THE FOLDER, on WorkflowAnalyzer.Application

**Comment by ramonck** [comment]
What's your Windows version and is your Windows a 64 bit machine?

**Comment by airdalle** [comment]
It's a Win7 Enterprise Sp1, and it's a 64 bit machine

**Comment by ramonck** [comment]
Hi @airdalle,
Sorry for the delay, I wanted to see if I could find something online before getting back to you on this.
I saw the following post in a Microsoft forum which is related to our problem here, I think it makes sense to try to repair the .Net Framework on the machine.
Please review and try it on your machine, if you have the solution please post here so others can know about it.
[https://social.msdn.microsoft.com/Forums/windows/en-US/73f55b96-0b30-4499-b777-ed00ebbaee5a/all-click-once-applications-throw-application-cannot-be-started-with-system-cannot-find-file?forum=winformssetup](url)
